# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Woof < Formula
  desc "woof"
  homepage "https://github.com/ondrejsikax/woof"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsikax/woof/releases/download/v0.2.0/woof_v0.2.0_darwin_amd64.tar.gz"
      sha256 "dcea7d0587bb994fe002bd4fbb8c6788e17ee1f89d63e9b6b02f07dab7c81958"

      def install
        bin.install "woof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsikax/woof/releases/download/v0.2.0/woof_v0.2.0_darwin_arm64.tar.gz"
      sha256 "e4b91100e3e1057dd051d973ec5329e8e395a8359bac01078d3b8ba80999d5d6"

      def install
        bin.install "woof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsikax/woof/releases/download/v0.2.0/woof_v0.2.0_linux_amd64.tar.gz"
      sha256 "b58d32c32509f5394f2fa7c8dc2e9400379587a708da945d4501ed473e9e1464"
      def install
        bin.install "woof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsikax/woof/releases/download/v0.2.0/woof_v0.2.0_linux_arm64.tar.gz"
      sha256 "1663ead190a588cbf530e89e9e583ebc337afab769250e6818bb7560652574c7"
      def install
        bin.install "woof"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsikax/woof
    EOS
  end

  test do
    system "#{bin}/woof version"
  end
end
