# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Woof < Formula
  desc "woof"
  homepage "https://github.com/ondrejsikax/woof"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsikax/woof/releases/download/v0.1.0/woof_v0.1.0_darwin_amd64.tar.gz"
      sha256 "21d5a2b6df4d70651099ab08cefa220de86b295402e775384285bcde05ee00b4"

      def install
        bin.install "woof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsikax/woof/releases/download/v0.1.0/woof_v0.1.0_darwin_arm64.tar.gz"
      sha256 "932d09e446f5691a22724df42d95b73a2ec2721a37941ef071b3e8c119b48fc7"

      def install
        bin.install "woof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsikax/woof/releases/download/v0.1.0/woof_v0.1.0_linux_amd64.tar.gz"
      sha256 "0717279e51baf80ce77f186fb434fb478b6a3d58b99ce4d0062a900c0757f68a"
      def install
        bin.install "woof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsikax/woof/releases/download/v0.1.0/woof_v0.1.0_linux_arm64.tar.gz"
      sha256 "54248ecbd51f2a651d9bd396f44716c73f96b91e5675d593caaf7b425dc656d9"
      def install
        bin.install "woof"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsikax/woof
    EOS
  end

  test do
    system "#{bin}/woof version"
  end
end
